plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/markjones/Library/CloudStorage/Dropbox/Claude Projects/Cowork/customisedartworks-brand/site/build"
publishOrigin = "config"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]